






















     
{ "AElig",  198  },   /* capital AE diphthong (ligature) */ 
{ "Aacgr",  0x0386 }, /* GREEK CAPITAL LETTER ALPHA TONOS */
{ "Aacute", 193  },   /* capital A, acute accent */ 
{ "Abreve", 0x102 }, /* LATIN CAPITAL LETTER A BREVE */
{ "Acirc",  194  },   /* capital A, circumflex accent */ 
{ "Acy",    0x0410 }, /* CYRILLIC CAPITAL LETTER A */
{ "Agr",    0x0391 }, /* GREEK CAPITAL LETTER ALPHA */
{ "Agrave", 192  },   /* capital A, grave accent */ 
{ "Alpha",  913  }, 
{ "Amacr",  0x100 }, /* LATIN CAPITAL LETTER A MACRON */
{ "Aogon",  0x104 }, /* LATIN CAPITAL LETTER A OGONEK */
{ "Aring",  197  },   /* capital A, ring */ 
{ "Atilde", 195  },   /* capital A, tilde */ 
{ "Auml",        196  },   /* capital A, dieresis or umlaut mark */ 
{ "Barwed", 0x2306 }, /* PERSPECTIVE */
{ "Bcy",    0x0411 }, /* CYRILLIC CAPITAL LETTER BE */
{ "Beta",        914  }, 
{ "Bgr",    0x0392 }, /* GREEK CAPITAL LETTER BETA */
{ "CHcy",   0x0427 }, /* CYRILLIC CAPITAL LETTER CHE */
{ "Cacute", 0x106 }, /* LATIN CAPITAL LETTER C ACUTE */
{ "Cap",    0x22D2 }, /* DOUBLE INTERSECTION */
{ "Ccaron", 0x010C }, /* LATIN CAPITAL LETTER C HACEK */
{ "Ccedil", 199  },   /* capital C, cedilla */ 
{ "Ccirc",  0x108 }, /* LATIN CAPITAL LETTER C CIRCUMFLEX */
{ "Cdot",   0x10a }, /* LATIN CAPITAL LETTER C DOT */
{ "Chi",         935  }, 
{ "Cup",    0x22D3 }, /* DOUBLE UNION */
{ "DJcy",   0x0402 }, /* CYRILLIC CAPITAL LETTER DJE */
{ "DScy",   0x0405 }, /* CYRILLIC CAPITAL LETTER DZE */
{ "DZcy",   0x040F }, /* CYRILLIC CAPITAL LETTER DZHE */
{ "Dagger", 8225 }, 
{ "Dcaron", 0x010E }, /* LATIN CAPITAL LETTER D HACEK */
{ "Dcy",    0x0414 }, /* CYRILLIC CAPITAL LETTER DE */
{ "Delta",  916  }, 
{ "Dgr",    0x0394 }, /* GREEK CAPITAL LETTER DELTA */
{ "Dot",    0xa8 }, /* SPACING DIAERESIS */
{ "DotDot", 0x20DC }, /* NON-SPACING FOUR DOTS ABOVE */
{ "Dstrok", 0x0110 }, /* LATIN CAPITAL LETTER D BAR */
{ "EEacgr", 0x0389 }, /* GREEK CAPITAL LETTER ETA TONOS */
{ "EEgr",   0x0397 }, /* GREEK CAPITAL LETTER ETA */
{ "ENG",    0x014A }, /* LATIN CAPITAL LETTER ENG */
{ "ETH",         208  },   /* capital Eth, Icelandic (Dstrok) */ 
{ "Eacgr",  0x0388 }, /* GREEK CAPITAL LETTER EPSILON TONOS */
{ "Eacute", 201  },   /* capital E, acute accent */ 
{ "Ecaron", 0x011A }, /* LATIN CAPITAL LETTER E HACEK */
{ "Ecirc",  202  },   /* capital E, circumflex accent */ 
{ "Ecy",    0x042D }, /* CYRILLIC CAPITAL LETTER REVERSED E */
{ "Edot",   0x0116 }, /* LATIN CAPITAL LETTER E DOT */
{ "Egr",    0x0395 }, /* GREEK CAPITAL LETTER EPSILON */
{ "Egrave", 200  },   /* capital E, grave accent */ 
{ "Emacr",  0x0112 }, /* LATIN CAPITAL LETTER E MACRON */
{ "Eogon",  0x0118 }, /* LATIN CAPITAL LETTER E OGONEK */
{ "Epsilon",     917  }, 
{ "Eta",         919  }, 
{ "Euml",        203  },   /* capital E, dieresis or umlaut mark */ 
{ "Fcy",    0x0424 }, /* CYRILLIC CAPITAL LETTER EF */
{ "GJcy",   0x0403 }, /* CYRILLIC CAPITAL LETTER GJE */
{ "Gamma",  915  },
{ "Gbreve", 0x011E }, /* LATIN CAPITAL LETTER G BREVE */
{ "Gcedil", 0x0122 }, /* LATIN CAPITAL LETTER G CEDILLA */
{ "Gcirc",  0x011C }, /* LATIN CAPITAL LETTER G CIRCUMFLEX */
{ "Gcy",    0x0413 }, /* CYRILLIC CAPITAL LETTER GE */
{ "Gdot",   0x0120 }, /* LATIN CAPITAL LETTER G DOT */
{ "Gg",     0x22D9 }, /* VERY MUCH GREATER THAN */
{ "Ggr",    0x0393 }, /* GREEK CAPITAL LETTER GAMMA */
{ "Gt",     0x226B }, /* MUCH GREATER THAN */
{ "HARDcy", 0x042A }, /* CYRILLIC CAPITAL LETTER HARD SIGN */
{ "Hcirc",  0x0124 }, /* LATIN CAPITAL LETTER H CIRCUMFLEX */
{ "Hstrok", 0x0126 }, /* LATIN CAPITAL LETTER H BAR */
{ "IEcy",   0x0415 }, /* CYRILLIC CAPITAL LETTER IE */
{ "IJlig",  0x0132 }, /* LATIN CAPITAL LETTER I J */
{ "IOcy",   0x0401 }, /* CYRILLIC CAPITAL LETTER IO */
{ "Iacgr",  0x038A }, /* GREEK CAPITAL LETTER IOTA TONOS */
{ "Iacute", 205  },   /* capital I, acute accent */ 
{ "Icirc",  206  },   /* capital I, circumflex accent */ 
{ "Icy",    0x0418 }, /* CYRILLIC CAPITAL LETTER II */
{ "Idigr",  0x03AA }, /* GREEK CAPITAL LETTER IOTA DIAERESIS */
{ "Idot",   0x0130 }, /* LATIN CAPITAL LETTER I DOT */
{ "Igr",    0x0399 }, /* GREEK CAPITAL LETTER IOTA */
{ "Igrave", 204  },   /* capital I, grave accent */ 
{ "Imacr",  0x012A }, /* LATIN CAPITAL LETTER I MACRON */
{ "Iogon",  0x012E }, /* LATIN CAPITAL LETTER I OGONEK */
{ "Iota",        921  }, 
{ "Itilde", 0x0128 }, /* LATIN CAPITAL LETTER I TILDE */
{ "Iukcy",  0x0406 }, /* CYRILLIC CAPITAL LETTER I */
{ "Iuml",        207  },   /* capital I, dieresis or umlaut mark */ 
{ "Jcirc",  0x0134 }, /* LATIN CAPITAL LETTER J CIRCUMFLEX */
{ "Jcy",    0x0419 }, /* CYRILLIC CAPITAL LETTER SHORT II */
{ "Jsercy", 0x0408 }, /* CYRILLIC CAPITAL LETTER JE */
{ "Jukcy",  0x0404 }, /* CYRILLIC CAPITAL LETTER E */
{ "KHcy",   0x0425 }, /* CYRILLIC CAPITAL LETTER KHA */
{ "KHgr",   0x03A7 }, /* GREEK CAPITAL LETTER CHI */
{ "KJcy",   0x040C }, /* CYRILLIC CAPITAL LETTER KJE */
{ "Kappa",  922  }, 
{ "Kcedil", 0x0136 }, /* LATIN CAPITAL LETTER K CEDILLA */
{ "Kcy",    0x041A }, /* CYRILLIC CAPITAL LETTER KA */
{ "Kgr",    0x039A }, /* GREEK CAPITAL LETTER KAPPA */
{ "LJcy",   0x0409 }, /* CYRILLIC CAPITAL LETTER LJE */
{ "Lacute", 0x0139 }, /* LATIN CAPITAL LETTER L ACUTE */
{ "Lambda", 0x039B }, /* GREEK CAPITAL LETTER LAMBDA */
{ "Larr",   0x219E }, /* LEFT TWO HEADED ARROW */
{ "Lcaron", 0x013D }, /* LATIN CAPITAL LETTER L HACEK */
{ "Lcedil", 0x013B }, /* LATIN CAPITAL LETTER L CEDILLA */
{ "Lcy",    0x041B }, /* CYRILLIC CAPITAL LETTER EL */
{ "Lgr",    0x039B }, /* GREEK CAPITAL LETTER LAMBDA */
{ "Ll",     0x22D8 }, /* VERY MUCH LESS THAN */
{ "Lmidot", 0x013F }, /* LATIN CAPITAL LETTER L WITH MIDDLE DOT */
{ "Lstrok", 0x0141 }, /* LATIN CAPITAL LETTER L SLASH */
{ "Lt",     0x226A }, /* MUCH LESS THAN */
{ "Mcy",    0x041C }, /* CYRILLIC CAPITAL LETTER EM */
{ "Mgr",    0x039C }, /* GREEK CAPITAL LETTER MU */
{ "Mu",          924  }, 
{ "NJcy",   0x040A }, /* CYRILLIC CAPITAL LETTER NJE */
{ "Nacute", 0x0143 }, /* LATIN CAPITAL LETTER N ACUTE */
{ "Ncaron", 0x0147 }, /* LATIN CAPITAL LETTER N HACEK */
{ "Ncedil", 0x0145 }, /* LATIN CAPITAL LETTER N CEDILLA */
{ "Ncy",    0x041D }, /* CYRILLIC CAPITAL LETTER EN */
{ "Ngr",    0x039D }, /* GREEK CAPITAL LETTER NU */
{ "Ntilde", 209  },   /* capital N, tilde */ 
{ "Nu",          925  }, 
{ "OElig",  338  }, 
{ "OHacgr", 0x038F }, /* GREEK CAPITAL LETTER OMEGA TONOS */
{ "OHgr",   0x03A9 }, /* GREEK CAPITAL LETTER OMEGA */
{ "Oacgr",  0x038C }, /* GREEK CAPITAL LETTER OMICRON TONOS */
{ "Oacute", 211  },   /* capital O, acute accent */ 
{ "Ocirc",  212  },   /* capital O, circumflex accent */ 
{ "Ocy",    0x041E }, /* CYRILLIC CAPITAL LETTER O */
{ "Odblac", 0x0150 }, /* LATIN CAPITAL LETTER O DOUBLE ACUTE */
{ "Ogr",    0x039F }, /* GREEK CAPITAL LETTER OMICRON */
{ "Ograve", 210  },   /* capital O, grave accent */ 
{ "Omacr",  0x014C }, /* LATIN CAPITAL LETTER O MACRON */
{ "Omega",  937  }, 
{ "Omicron",     927  }, 
{ "Oslash", 216  },   /* capital O, slash */ 
{ "Otilde", 213  },   /* capital O, tilde */ 
{ "Ouml",        214  },   /* capital O, dieresis or umlaut mark */ 
{ "PHgr",   0x03A6 }, /* GREEK CAPITAL LETTER PHI */
{ "PSgr",   0x03A8 }, /* GREEK CAPITAL LETTER PSI */
{ "Pcy",    0x041F }, /* CYRILLIC CAPITAL LETTER PE */
{ "Pgr",    0x03A0 }, /* GREEK CAPITAL LETTER PI */
{ "Phi",         934  }, 
{ "Pi",          928  }, 
{ "Prime",  8243 }, 
{ "Psi",         936  }, 
{ "Racute", 0x0154 }, /* LATIN CAPITAL LETTER R ACUTE */
{ "Rarr",   0x21A0 }, /* RIGHT TWO HEADED ARROW */
{ "Rcaron", 0x0158 }, /* LATIN CAPITAL LETTER R HACEK */
{ "Rcedil", 0x0156 }, /* LATIN CAPITAL LETTER R CEDILLA */
{ "Rcy",    0x0420 }, /* CYRILLIC CAPITAL LETTER ER */
{ "Rgr",    0x03A1 }, /* GREEK CAPITAL LETTER RHO */
{ "Rho",         929  }, 
{ "SHCHcy", 0x0429 }, /* CYRILLIC CAPITAL LETTER SHCHA */
{ "SHcy",   0x0428 }, /* CYRILLIC CAPITAL LETTER SHA */
{ "SOFTcy", 0x042C }, /* CYRILLIC CAPITAL LETTER SOFT SIGN */
{ "Sacute", 0x015A }, /* LATIN CAPITAL LETTER S ACUTE */
{ "Scaron", 352  }, 
{ "Scedil", 0x015E }, /* LATIN CAPITAL LETTER S CEDILLA */
{ "Scirc",  0x015C }, /* LATIN CAPITAL LETTER S CIRCUMFLEX */
{ "Scy",    0x0421 }, /* CYRILLIC CAPITAL LETTER ES */
{ "Sgr",    0x03A3 }, /* GREEK CAPITAL LETTER SIGMA */
{ "Sigma",  931  }, 
{ "Sub",    0x22D0 }, /* DOUBLE SUBSET */
{ "Sup",    0x22D1 }, /* DOUBLE SUPERSET */
{ "THORN",  222  },   /* capital THORN, Icelandic */ 
{ "THgr",   0x0398 }, /* GREEK CAPITAL LETTER THETA */
{ "TSHcy",  0x040B }, /* CYRILLIC CAPITAL LETTER TSHE */
{ "TScy",   0x0426 }, /* CYRILLIC CAPITAL LETTER TSE */
{ "Tau",         932  }, 
{ "Tcaron", 0x0164 }, /* LATIN CAPITAL LETTER T HACEK */
{ "Tcedil", 0x0162 }, /* LATIN CAPITAL LETTER T CEDILLA */
{ "Tcy",    0x0422 }, /* CYRILLIC CAPITAL LETTER TE */
{ "Tgr",    0x03A4 }, /* GREEK CAPITAL LETTER TAU */
{ "Theta",  920  }, 
{ "Tstrok", 0x0166 }, /* LATIN CAPITAL LETTER T BAR */
{ "Uacgr",  0x038E }, /* GREEK CAPITAL LETTER UPSILON TONOS */
{ "Uacute", 218  },   /* capital U, acute accent */ 
{ "Ubrcy",  0x040E }, /* CYRILLIC CAPITAL LETTER SHORT U */
{ "Ubreve", 0x016C }, /* LATIN CAPITAL LETTER U BREVE */
{ "Ucirc",  219  },   /* capital U, circumflex accent */ 
{ "Ucy",    0x0423 }, /* CYRILLIC CAPITAL LETTER U */
{ "Udblac", 0x0170 }, /* LATIN CAPITAL LETTER U DOUBLE ACUTE */
{ "Udigr",  0x03AB }, /* GREEK CAPITAL LETTER UPSILON DIAERESIS */
{ "Ugr",    0x03A5 }, /* GREEK CAPITAL LETTER UPSILON */
{ "Ugrave", 217  },   /* capital U, grave accent */ 
{ "Umacr",  0x016A }, /* LATIN CAPITAL LETTER U MACRON */
{ "Uogon",  0x0172 }, /* LATIN CAPITAL LETTER U OGONEK */
{ "Upsi",   0x03A5 }, /* GREEK CAPITAL LETTER UPSILON */
{ "Upsilon",     933  }, 
{ "Uring",  0x016E }, /* LATIN CAPITAL LETTER U RING */
{ "Utilde", 0x0168 }, /* LATIN CAPITAL LETTER U TILDE */
{ "Uuml",        220  },   /* capital U, dieresis or umlaut mark */ 
{ "Vcy",    0x0412 }, /* CYRILLIC CAPITAL LETTER VE */
{ "Vdash",  0x22A9 }, /* FORCES */
{ "Verbar", 0x2016 }, /* DOUBLE VERTICAL BAR */
{ "Vvdash", 0x22AA }, /* TRIPLE VERTICAL BAR RIGHT TURNSTILE */
{ "Wcirc",  0x0174 }, /* LATIN CAPITAL LETTER W CIRCUMFLEX */
{ "Xgr",    0x039E }, /* GREEK CAPITAL LETTER XI */
{ "Xi",          926  }, 
{ "YAcy",   0x042F }, /* CYRILLIC CAPITAL LETTER IA */
{ "YIcy",   0x0407 }, /* CYRILLIC CAPITAL LETTER YI */
{ "YUcy",   0x042E }, /* CYRILLIC CAPITAL LETTER IU */
{ "Yacute", 221  },   /* capital Y, acute accent */ 
{ "Ycirc",  0x0176 }, /* LATIN CAPITAL LETTER Y CIRCUMFLEX */
{ "Ycy",    0x042B }, /* CYRILLIC CAPITAL LETTER YERI */
{ "Yuml",        376  }, 
{ "ZHcy",   0x0416 }, /* CYRILLIC CAPITAL LETTER ZHE */
{ "Zacute", 0x0179 }, /* LATIN CAPITAL LETTER Z ACUTE */
{ "Zcaron", 0x017D }, /* LATIN CAPITAL LETTER Z HACEK */
{ "Zcy",    0x0417 }, /* CYRILLIC CAPITAL LETTER ZE */
{ "Zdot",   0x017B }, /* LATIN CAPITAL LETTER Z DOT */
{ "Zeta",        918  }, 
{ "Zgr",    0x0396 }, /* GREEK CAPITAL LETTER ZETA */
{ "aacgr",  0x03AC }, /* GREEK SMALL LETTER ALPHA TONOS */
{ "aacute", 225  },   /* small a, acute accent */ 
{ "abreve", 0x103 }, /* LATIN SMALL LETTER A BREVE */
{ "acirc",  226  },   /* small a, circumflex accent */ 
{ "acute",  180  },   /* spacing acute (96) */
{ "acy",    0x0430 }, /* CYRILLIC SMALL LETTER A */
{ "aelig",  230  },   /* small ae diphthong (ligature) */ 
{ "agr",    0x03B1 }, /* GREEK SMALL LETTER ALPHA */
{ "agrave", 224  },   /* small a, grave accent */ 
{ "alefsym",     8501 }, 
{ "aleph",  0x2135 }, /* FIRST TRANSFINITE CARDINAL */
{ "alpha",  945  }, 
{ "amacr",  0x101 }, /* LATIN SMALL LETTER A MACRON */
{ "amalg",  0x2210 }, /* N-ARY COPRODUCT */
{ "amp",         '&'  },
{ "and",         8743 }, 
{ "ang",         8736 }, 
{ "ang90",  0x221F }, /* RIGHT ANGLE */
{ "angmsd", 0x2221 }, /* MEASURED ANGLE */
{ "angsph", 0x2222 }, /* SPHERICAL ANGLE */
{ "angst",  0x212B }, /* ANGSTROM UNIT */
{ "aogon",  0x105 }, /* LATIN SMALL LETTER A OGONEK */
{ "ap",     0x2248 }, /* ALMOST EQUAL TO */
{ "ape",    0x224A }, /* ALMOST EQUAL OR EQUAL TO */
{ "apos",   0x02BC }, /* MODIFIER LETTER APOSTROPHE */
{ "aring",  229  },   /* small a, ring */
{ "ast",    0x2a }, /* ASTERISK */
{ "asymp",  8776 }, 
{ "atilde", 227  },   /* small a, tilde */
{ "auml",        228  },   /* small a, dieresis or umlaut mark */ 
{ "barwed", 0x22BC }, /* NAND */
{ "bcong",  0x224C }, /* ALL EQUAL TO */
{ "bcy",    0x0431 }, /* CYRILLIC SMALL LETTER BE */
{ "bdquo",  8222 }, 
{ "becaus", 0x2235 }, /* BECAUSE */
{ "bepsi",  0x220D }, /* SMALL CONTAINS AS MEMBER */
{ "bernou", 0x212C }, /* SCRIPT B */
{ "beta",        946  }, 
{ "beth",   0x2136 }, /* SECOND TRANSFINITE CARDINAL */
{ "bgr",    0x03B2 }, /* GREEK SMALL LETTER BETA */
{ "blank",  0x2423 }, /* OPEN BOX */
{ "blk12",  0x2592 }, /* MEDIUM SHADE */
{ "blk14",  0x2591 }, /* LIGHT SHADE */
{ "blk34",  0x2593 }, /* DARK SHADE */
{ "block",  0x2588 }, /* FULL BLOCK */
{ "bottom", 0x22A5 }, /* UP TACK */
{ "bowtie", 0x22C8 }, /* BOWTIE */
{ "boxDL",  0x2557 }, /* FORMS DOUBLE DOWN AND LEFT */
{ "boxDR",  0x2554 }, /* FORMS DOUBLE DOWN AND RIGHT */
{ "boxDl",  0x2556 }, /* FORMS DOWN DOUBLE AND LEFT SINGLE */
{ "boxDr",  0x2553 }, /* FORMS DOWN DOUBLE AND RIGHT SINGLE */
{ "boxH",   0x2550 }, /* FORMS DOUBLE HORIZONTAL */
{ "boxHD",  0x2566 }, /* FORMS DOUBLE DOWN AND HORIZONTAL */
{ "boxHU",  0x2569 }, /* FORMS DOUBLE UP AND HORIZONTAL */
{ "boxHd",  0x2564 }, /* FORMS DOWN SINGLE AND HORIZONTAL DOUBLE */
{ "boxHu",  0x2567 }, /* FORMS UP SINGLE AND HORIZONTAL DOUBLE */
{ "boxUL",  0x255D }, /* FORMS DOUBLE UP AND LEFT */
{ "boxUR",  0x255A }, /* FORMS DOUBLE UP AND RIGHT */
{ "boxUl",  0x255C }, /* FORMS UP DOUBLE AND LEFT SINGLE */
{ "boxUr",  0x2559 }, /* FORMS UP DOUBLE AND RIGHT SINGLE */
{ "boxV",   0x2551 }, /* FORMS DOUBLE VERTICAL */
{ "boxVH",  0x256C }, /* FORMS DOUBLE VERTICAL AND HORIZONTAL */
{ "boxVL",  0x2563 }, /* FORMS DOUBLE VERTICAL AND LEFT */
{ "boxVR",  0x2560 }, /* FORMS DOUBLE VERTICAL AND RIGHT */
{ "boxVh",  0x256B }, /* FORMS VERTICAL DOUBLE AND HORIZONTAL SINGLE */
{ "boxVl",  0x2562 }, /* FORMS VERTICAL DOUBLE AND LEFT SINGLE */
{ "boxVr",  0x255F }, /* FORMS VERTICAL DOUBLE AND RIGHT SINGLE */
{ "boxdL",  0x2555 }, /* FORMS DOWN SINGLE AND LEFT DOUBLE */
{ "boxdR",  0x2552 }, /* FORMS DOWN SINGLE AND RIGHT DOUBLE */
{ "boxdl",  0x2510 }, /* FORMS LIGHT DOWN AND LEFT */
{ "boxdr",  0x250C }, /* FORMS LIGHT DOWN AND RIGHT */
{ "boxh",   0x2500 }, /* FORMS LIGHT HORIZONTAL */
{ "boxhD",  0x2565 }, /* FORMS DOWN DOUBLE AND HORIZONTAL SINGLE */
{ "boxhU",  0x2568 }, /* FORMS UP DOUBLE AND HORIZONTAL SINGLE */
{ "boxhd",  0x252C }, /* FORMS LIGHT DOWN AND HORIZONTAL */
{ "boxhu",  0x2534 }, /* FORMS LIGHT UP AND HORIZONTAL */
{ "boxuL",  0x255B }, /* FORMS UP SINGLE AND LEFT DOUBLE */
{ "boxuR",  0x2558 }, /* FORMS UP SINGLE AND RIGHT DOUBLE */
{ "boxul",  0x2518 }, /* FORMS LIGHT UP AND LEFT */
{ "boxur",  0x2514 }, /* FORMS LIGHT UP AND RIGHT */
{ "boxv",   0x2502 }, /* FORMS LIGHT VERTICAL */
{ "boxvH",  0x256A }, /* FORMS VERTICAL SINGLE AND HORIZONTAL DOUBLE */
{ "boxvL",  0x2561 }, /* FORMS VERTICAL SINGLE AND LEFT DOUBLE */
{ "boxvR",  0x255E }, /* FORMS VERTICAL SINGLE AND RIGHT DOUBLE */
{ "boxvh",  0x253C }, /* FORMS LIGHT VERTICAL AND HORIZONTAL */
{ "boxvl",  0x2524 }, /* FORMS LIGHT VERTICAL AND LEFT */
{ "boxvr",  0x251C }, /* FORMS LIGHT VERTICAL AND RIGHT */
{ "bprime", 0x2035 }, /* REVERSED PRIME */
{ "breve",  0x02D8 }, /* SPACING BREVE */
{ "brvbar",      166  },   /* broken vertical bar, (brkbar) */
{ "bsim",   0x223D }, /* REVERSED TILDE */
{ "bsime",  0x22CD }, /* REVERSED TILDE EQUALS */
{ "bsol",   0x5c }, /* BACKSLASH */
{ "bull",        8226 }, 
{ "bump",   0x224E }, /* GEOMETRICALLY EQUIVALENT TO */
{ "bumpe",  0x224F }, /* DIFFERENCE BETWEEN */
{ "cacute", 0x107 }, /* LATIN SMALL LETTER C ACUTE */
{ "cap",         8745 }, 
{ "caret",  0x2041 }, /* CARET INSERTION POINT */
{ "caron",  0x02C7 }, /* MODIFIER LETTER HACEK */
{ "ccaron", 0x010D }, /* LATIN SMALL LETTER C HACEK */
{ "ccedil", 231  },   /* small c, cedilla */ 
{ "ccirc",  0x109 }, /* LATIN SMALL LETTER C CIRCUMFLEX */
{ "cdot",   0x10b }, /* LATIN SMALL LETTER C DOT */
{ "cedil",  184  },   /* spacing cedilla */
{ "cent",        162  },   /* cent sign */
{ "chcy",   0x0447 }, /* CYRILLIC SMALL LETTER CHE */
{ "check",  0x2713 }, /* CHECK MARK */
{ "chi",         967  }, 
{ "cir",    0x25CB }, /* WHITE CIRCLE */
{ "circ",   0x5e /*710*/  }, /* SPACING CIRCUMFLEX */
{ "cire",   0x2257 }, /* RING EQUAL TO */
{ "clubs",  9827 }, 
{ "colon",  0x3a }, /* COLON */
{ "colone", 0x2254 }, /* COLON EQUAL */
{ "comma",  0x2c }, /* COMMA */
{ "commat", 0x40 }, /* COMMERCIAL AT */
{ "comp",   0x2201 }, /* COMPLEMENT */
{ "compfn", 0x2218 }, /* RING OPERATOR */
{ "cong",        8773 }, 
{ "conint", 0x222E }, /* CONTOUR INTEGRAL */
{ "coprod", 0x2210 }, /* N-ARY COPRODUCT */
{ "copy",        169  },   /* copyright sign */
{ "copysr", 0x2117 }, /* SOUND RECORDING COPYRIGHT */
{ "crarr",  8629 }, 
{ "cross",  0x2717 }, /* BALLOT X */
{ "cuepr",  0x22DE }, /* EQUAL TO OR PRECEDES */
{ "cuesc",  0x22DF }, /* EQUAL TO OR SUCCEEDS */
{ "cularr", 0x21B6 }, /* ANTICLOCKWISE TOP SEMICIRCLE ARROW */
{ "cup",         8746 }, 
{ "cupre",  0x227C }, /* PRECEDES OR EQUAL TO */
{ "curarr", 0x21B7 }, /* CLOCKWISE TOP SEMICIRCLE ARROW */
{ "curren",      164  },   /* currency sign */
{ "cuvee",  0x22CE }, /* CURLY LOGICAL OR */
{ "cuwed",  0x22CF }, /* CURLY LOGICAL AND */
{ "dArr",        8659 }, 
{ "dagger", 8224 }, 
{ "daleth", 0x2138 }, /* FOURTH TRANSFINITE CARDINAL */
{ "darr",        8595 }, 
{ "darr2",  0x21CA }, /* DOWN PAIRED ARROWS */
{ "dash",   0x2010 }, /* HYPHEN */
{ "dashv",  0x22A3 }, /* LEFT TACK */
{ "dblac",  0x02DD }, /* SPACING DOUBLE ACUTE */
{ "dcaron", 0x010F }, /* LATIN SMALL LETTER D HACEK */
{ "dcy",    0x0434 }, /* CYRILLIC SMALL LETTER DE */
{ "deg",         176  },   /* degree sign */
{ "delta",  948  }, 
{ "dgr",    0x03B4 }, /* GREEK SMALL LETTER DELTA */
{ "dharl",  0x21C3 }, /* DOWN HARPOON WITH BARB LEFT */
{ "dharr",  0x21C2 }, /* DOWN HARPOON WITH BARB RIGHT */
{ "diam",   0x22C4 }, /* DIAMOND OPERATOR */
{ "diams",  0x2662 }, /* WHITE DIAMOND SUIT */
{ "die",    0xa8 }, /* SPACING DIAERESIS */
{ "divide", 247  },   /* division sign */
{ "divonx", 0x22C7 }, /* DIVISION TIMES */
{ "djcy",   0x0452 }, /* CYRILLIC SMALL LETTER DJE */
{ "dlarr",  0x2199 }, /* LOWER LEFT ARROW */
{ "dlcorn", 0x231E }, /* BOTTOM LEFT CORNER */
{ "dlcrop", 0x230D }, /* BOTTOM LEFT CROP */
{ "dollar", 0x24 }, /* DOLLAR SIGN */
{ "dot",    0x02D9 }, /* SPACING DOT ABOVE */
{ "drarr",  0x2198 }, /* LOWER RIGHT ARROW */
{ "drcorn", 0x231F }, /* BOTTOM RIGHT CORNER */
{ "drcrop", 0x230C }, /* BOTTOM RIGHT CROP */
{ "dscy",   0x0455 }, /* CYRILLIC SMALL LETTER DZE */
{ "dstrok", 0x0111 }, /* LATIN SMALL LETTER D BAR */
{ "dtri",   0x25BF }, /* WHITE DOWN POINTING SMALL TRIANGLE */
{ "dtrif",  0x25BE }, /* BLACK DOWN POINTING SMALL TRIANGLE */
{ "dzcy",   0x045F }, /* CYRILLIC SMALL LETTER DZHE */
{ "eDot",   0x2251 }, /* GEOMETRICALLY EQUAL TO */
{ "eacgr",  0x03AD }, /* GREEK SMALL LETTER EPSILON TONOS */
{ "eacute", 233  },   /* small e, acute accent */ 
{ "ecaron", 0x011B }, /* LATIN SMALL LETTER E HACEK */
{ "ecir",   0x2256 }, /* RING IN EQUAL TO */
{ "ecirc",  234  },   /* small e, circumflex accent */ 
{ "ecolon", 0x2255 }, /* EQUAL COLON */
{ "ecy",    0x044D }, /* CYRILLIC SMALL LETTER REVERSED E */
{ "edot",   0x0117 }, /* LATIN SMALL LETTER E DOT */
{ "eeacgr", 0x03AE }, /* GREEK SMALL LETTER ETA TONOS */
{ "eegr",   0x03B7 }, /* GREEK SMALL LETTER ETA */
{ "efDot",  0x2252 }, /* APPROXIMATELY EQUAL TO OR THE IMAGE OF */
{ "egr",    0x03B5 }, /* GREEK SMALL LETTER EPSILON */
{ "egrave", 232  },   /* small e, grave accent */ 
{ "egs",    0x22DD }, /* EQUAL TO OR GREATER THAN */
{ "ell",    0x2113 }, /* SCRIPT SMALL L */
{ "els",    0x22DC }, /* EQUAL TO OR LESS THAN */
{ "emacr",  0x0113 }, /* LATIN SMALL LETTER E MACRON */
{ "empty",  0x2205 }, /* EMPTY SET */
{ "emsp",        8195 },   /* em space */
{ "emsp13", 0x2004 }, /* THREE-PER-EM SPACE */
{ "emsp14", 0x2005 }, /* FOUR-PER-EM SPACE */
{ "eng",    0x014B }, /* LATIN SMALL LETTER ENG */
{ "ensp",        8194 },   /* en space */
{ "eogon",  0x0119 }, /* LATIN SMALL LETTER E OGONEK */
{ "epsi",   0x03B5 }, /* GREEK SMALL LETTER EPSILON */
{ "epsilon",     949  }, 
{ "epsis",  0x220A }, /* SMALL ELEMENT OF */
{ "equals", 0x3d }, /* EQUALS SIGN */
{ "equiv",  0x2261 }, /* IDENTICAL TO */
{ "erDot",  0x2253 }, /* IMAGE OF OR APPROXIMATELY EQUAL TO */
{ "esdot",  0x2250 }, /* APPROACHES THE LIMIT */
{ "eta",    0x03B7 }, /* GREEK SMALL LETTER ETA */
{ "eth",         240  },   /* small eth, Icelandic */ 
{ "euml",        235  },   /* small e, dieresis or umlaut mark */ 
{ "euro",        8364 }, 
{ "excl",   0x21 }, /* EXCLAMATION MARK */
{ "exist",  0x2203 }, /* THERE EXISTS */
{ "fcy",    0x0444 }, /* CYRILLIC SMALL LETTER EF */
{ "female", 0x2640 }, /* FEMALE SIGN */
{ "flat",   0x266D }, /* FLAT */
{ "fnof",   0x0192 }, /* LATIN SMALL LETTER SCRIPT F */
{ "forall", 0x2200 }, /* FOR ALL */
{ "fork",   0x22D4 }, /* PITCHFORK */
{ "frac12", 189  },   /* fraction 1/2 */
{ "frac13", 0x2153 }, /* FRACTION ONE THIRD */
{ "frac14", 188  },   /* fraction 1/4 */
{ "frac15", 0x2155 }, /* FRACTION ONE FIFTH */
{ "frac16", 0x2159 }, /* FRACTION ONE SIXTH */
{ "frac18", 0x215B }, /* FRACTION ONE EIGHTH */
{ "frac23", 0x2154 }, /* FRACTION TWO THIRDS */
{ "frac25", 0x2156 }, /* FRACTION TWO FIFTHS */
{ "frac34", 190  },   /* fraction 3/4 */
{ "frac35", 0x2157 }, /* FRACTION THREE FIFTHS */
{ "frac38", 0x215C }, /* FRACTION THREE EIGHTHS */
{ "frac45", 0x2158 }, /* FRACTION FOUR FIFTHS */
{ "frac56", 0x215A }, /* FRACTION FIVE SIXTHS */
{ "frac58", 0x215D }, /* FRACTION FIVE EIGHTHS */
{ "frac78", 0x215E }, /* FRACTION SEVEN EIGHTHS */
{ "frasl",  8260 }, 
{ "frown",  0x2322 }, /* FROWN */
{ "gE",     0x2267 }, /* GREATER THAN OVER EQUAL TO */
{ "gamma",  947  }, 
{ "gammad", 0x03DD }, /* GREEK SMALL LETTER DIGAMMA */
{ "gbreve", 0x011F }, /* LATIN SMALL LETTER G BREVE */
{ "gcedil", 0x0123 }, /* LATIN SMALL LETTER G CEDILLA */
{ "gcirc",  0x011D }, /* LATIN SMALL LETTER G CIRCUMFLEX */
{ "gcy",    0x0433 }, /* CYRILLIC SMALL LETTER GE */
{ "gdot",   0x0121 }, /* LATIN SMALL LETTER G DOT */
{ "ge",     0x2265 }, /* GREATER THAN OR EQUAL TO */
{ "gel",    0x22DB }, /* GREATER THAN EQUAL TO OR LESS THAN */
{ "ges",    0x2265 }, /* GREATER THAN OR EQUAL TO */
{ "ggr",    0x03B3 }, /* GREEK SMALL LETTER GAMMA */
{ "gimel",  0x2137 }, /* THIRD TRANSFINITE CARDINAL */
{ "gjcy",   0x0453 }, /* CYRILLIC SMALL LETTER GJE */
{ "gl",     0x2277 }, /* GREATER THAN OR LESS THAN */
{ "gnE",    0x2269 }, /* GREATER THAN BUT NOT EQUAL TO */
{ "gnsim",  0x22E7 }, /* GREATER THAN BUT NOT EQUIVALENT TO */
{ "grave",  0x60 }, /* SPACING GRAVE */
{ "gsdot",  0x22D7 }, /* GREATER THAN WITH DOT */
{ "gsim",   0x2273 }, /* GREATER THAN OR EQUIVALENT TO */
{ "gt",          '>'  },
{ "gvnE",   0x2269 }, /* GREATER THAN BUT NOT EQUAL TO */
{ "hArr",        8660 }, 
{ "hairsp", 0x200A }, /* HAIR SPACE */
{ "hamilt", 0x210B }, /* SCRIPT H */
{ "hardcy", 0x044A }, /* CYRILLIC SMALL LETTER HARD SIGN */
{ "harr",        8596 }, 
{ "harrw",  0x21AD }, /* LEFT RIGHT WAVE ARROW */
{ "hcirc",  0x0125 }, /* LATIN SMALL LETTER H CIRCUMFLEX */
{ "hearts", 0x2661 }, /* WHITE HEART SUIT */
{ "hellip", 0x2026 }, /* HORIZONTAL ELLIPSIS */
{ "hibar",  175  },   /* spacing macron */
{ "horbar", 0x2015 }, /* QUOTATION DASH */
{ "hstrok", 0x0127 }, /* LATIN SMALL LETTER H BAR */
{ "hybull", 0x2043 }, /* HYPHEN BULLET */
{ "hyphen", 0x2d }, /* HYPHEN-MINUS */
{ "iacgr",  0x03AF }, /* GREEK SMALL LETTER IOTA TONOS */
{ "iacute", 237  },   /* small i, acute accent */ 
{ "icirc",  238  },   /* small i, circumflex accent */ 
{ "icy",    0x0438 }, /* CYRILLIC SMALL LETTER II */
{ "idiagr", 0x0390 }, /* GREEK SMALL LETTER IOTA DIAERESIS TONOS */
{ "idigr",  0x03CA }, /* GREEK SMALL LETTER IOTA DIAERESIS */
{ "iecy",   0x0435 }, /* CYRILLIC SMALL LETTER IE */
{ "iexcl",       161  },   /* inverted exclamation mark */
{ "iff",    0x21D4 }, /* LEFT RIGHT DOUBLE ARROW */
{ "igr",    0x03B9 }, /* GREEK SMALL LETTER IOTA */
{ "igrave", 236  },   /* small i, grave accent */ 
{ "ijlig",  0x0133 }, /* LATIN SMALL LETTER I J */
{ "imacr",  0x012B }, /* LATIN SMALL LETTER I MACRON */
{ "image",  0x2111 }, /* BLACK-LETTER I */
{ "incare", 0x2105 }, /* CARE OF */
{ "infin",  0x221E }, /* INFINITY */
{ "inodot", 0x0131 }, /* LATIN SMALL LETTER DOTLESS I */
{ "int",         8747 }, 
{ "intcal", 0x22BA }, /* INTERCALATE */
{ "iocy",   0x0451 }, /* CYRILLIC SMALL LETTER IO */
{ "iogon",  0x012F }, /* LATIN SMALL LETTER I OGONEK */
{ "iota",   0x03B9 }, /* GREEK SMALL LETTER IOTA */
{ "iquest", 191  },   /* inverted question mark */
{ "isin",   0x2208 }, /* ELEMENT OF */
{ "itilde", 0x0129 }, /* LATIN SMALL LETTER I TILDE */
{ "iukcy",  0x0456 }, /* CYRILLIC SMALL LETTER I */
{ "iuml",        239  },   /* small i, dieresis or umlaut mark */ 
{ "jcirc",  0x0135 }, /* LATIN SMALL LETTER J CIRCUMFLEX */
{ "jcy",    0x0439 }, /* CYRILLIC SMALL LETTER SHORT II */
{ "jsercy", 0x0458 }, /* CYRILLIC SMALL LETTER JE */
{ "jukcy",  0x0454 }, /* CYRILLIC SMALL LETTER E */
{ "kappa",  0x03BA }, /* GREEK SMALL LETTER KAPPA */
{ "kappav", 0x03F0 }, /* GREEK SMALL LETTER SCRIPT KAPPA */
{ "kcedil", 0x0137 }, /* LATIN SMALL LETTER K CEDILLA */
{ "kcy",    0x043A }, /* CYRILLIC SMALL LETTER KA */
{ "kgr",    0x03BA }, /* GREEK SMALL LETTER KAPPA */
{ "kgreen", 0x0138 }, /* LATIN SMALL LETTER KRA */
{ "khcy",   0x0445 }, /* CYRILLIC SMALL LETTER KHA */
{ "khgr",   0x03C7 }, /* GREEK SMALL LETTER CHI */
{ "kjcy",   0x045C }, /* CYRILLIC SMALL LETTER KJE */
{ "lAarr",  0x21DA }, /* LEFT TRIPLE ARROW */
{ "lArr",   0x21D0 }, /* LEFT DOUBLE ARROW */
{ "lE",     0x2266 }, /* LESS THAN OVER EQUAL TO */
{ "lacute", 0x013A }, /* LATIN SMALL LETTER L ACUTE */
{ "lagran", 0x2112 }, /* SCRIPT L */
{ "lambda", 0x03BB }, /* GREEK SMALL LETTER LAMBDA */
{ "lang",   0x2329 }, /* BRA */
{ "laquo",  171  },   /* angle quotation mark, left */
{ "larr",   0x2190 }, /* LEFT ARROW */
{ "larr2",  0x21C7 }, /* LEFT PAIRED ARROWS */
{ "larrhk", 0x21A9 }, /* LEFT ARROW WITH HOOK */
{ "larrlp", 0x21AB }, /* LEFT ARROW WITH LOOP */
{ "larrtl", 0x21A2 }, /* LEFT ARROW WITH TAIL */
{ "lcaron", 0x013E }, /* LATIN SMALL LETTER L HACEK */
{ "lcedil", 0x013C }, /* LATIN SMALL LETTER L CEDILLA */
{ "lceil",  0x2308 }, /* LEFT CEILING */
{ "lcub",   0x7b }, /* OPENING CURLY BRACKET */
{ "lcy",    0x043B }, /* CYRILLIC SMALL LETTER EL */
{ "ldot",   0x22D6 }, /* LESS THAN WITH DOT */
{ "ldquo",  0x201C }, /* DOUBLE TURNED COMMA QUOTATION MARK */
{ "ldquor", 0x201E }, /* LOW DOUBLE COMMA QUOTATION MARK */
{ "le",     0x2264 }, /* LESS THAN OR EQUAL TO */
{ "leg",    0x22DA }, /* LESS THAN EQUAL TO OR GREATER THAN */
{ "les",    0x2264 }, /* LESS THAN OR EQUAL TO */
{ "lfloor", 0x230A }, /* LEFT FLOOR */
{ "lg",     0x2276 }, /* LESS THAN OR GREATER THAN */
{ "lgr",    0x03BB }, /* GREEK SMALL LETTER LAMBDA */
{ "lhard",  0x21BD }, /* LEFT HARPOON WITH BARB DOWN */
{ "lharu",  0x21BC }, /* LEFT HARPOON WITH BARB UP */
{ "lhblk",  0x2584 }, /* LOWER HALF BLOCK */
{ "ljcy",   0x0459 }, /* CYRILLIC SMALL LETTER LJE */
{ "lmidot", 0x0140 }, /* LATIN SMALL LETTER L WITH MIDDLE DOT */
{ "lnE",    0x2268 }, /* LESS THAN BUT NOT EQUAL TO */
{ "lnsim",  0x22E6 }, /* LESS THAN BUT NOT EQUIVALENT TO */
{ "lowast", 8727 }, 
{ "lowbar", 0x5f }, /* SPACING UNDERSCORE */
{ "loz",    0x2727 }, /* WHITE FOUR POINTED STAR */
{ "lozf",   0x2726 }, /* BLACK FOUR POINTED STAR */
{ "lpar",   0x28 }, /* OPENING PARENTHESIS */
{ "lrarr2", 0x21C6 }, /* LEFT ARROW OVER RIGHT ARROW */
{ "lrhar2", 0x21CB }, /* LEFT HARPOON OVER RIGHT HARPOON */
{ "lrm",         8206 },   /* left-to-right mark */
{ "lsaquo", 8249 }, 
{ "lsh",    0x21B0 }, /* UP ARROW WITH TIP LEFT */
{ "lsim",   0x2272 }, /* LESS THAN OR EQUIVALENT TO */
{ "lsqb",   0x5b }, /* OPENING SQUARE BRACKET */
{ "lsquo",  0x2018 }, /* SINGLE TURNED COMMA QUOTATION MARK */
{ "lsquor", 0x201A }, /* LOW SINGLE COMMA QUOTATION MARK */
{ "lstrok", 0x0142 }, /* LATIN SMALL LETTER L SLASH */
{ "lt",          '<'  },
{ "lthree", 0x22CB }, /* LEFT SEMIDIRECT PRODUCT */
{ "ltimes", 0x22C9 }, /* LEFT NORMAL FACTOR SEMIDIRECT PRODUCT */
{ "ltri",   0x25C3 }, /* WHITE LEFT POINTING SMALL TRIANGLE */
{ "ltrie",  0x22B4 }, /* NORMAL SUBGROUP OF OR EQUAL TO */
{ "ltrif",  0x25C2 }, /* BLACK LEFT POINTING SMALL TRIANGLE */
{ "lvnE",   0x2268 }, /* LESS THAN BUT NOT EQUAL TO */
{ "macr",   175  },   /* spacing macron */
{ "male",   0x2642 }, /* MALE SIGN */
{ "malt",   0x2720 }, /* MALTESE CROSS */
{ "map",    0x21A6 }, /* RIGHT ARROW FROM BAR */
{ "marker", 0x25AE }, /* BLACK VERTICAL RECTANGLE */
{ "mcy",    0x043C }, /* CYRILLIC SMALL LETTER EM */
{ "mdash",  0x2014 }, /* EM DASH */
{ "mgr",    0x03BC }, /* GREEK SMALL LETTER MU */
{ "micro",  181  },   /* micro sign */
{ "mid",    0x2223 }, /* DIVIDES */
{ "middot", 183  },   /* middle dot */
{ "minus",  0x2212 }, /* MINUS SIGN */
{ "minusb", 0x229F }, /* SQUARED MINUS */
{ "mldr",   0x2026 }, /* HORIZONTAL ELLIPSIS */
{ "mnplus", 0x2213 }, /* MINUS-OR-PLUS SIGN */
{ "models", 0x22A7 }, /* MODELS */
{ "mu",     0x03BC }, /* GREEK SMALL LETTER MU */
{ "mumap",  0x22B8 }, /* MULTIMAP */
{ "nVDash", 0x22AF }, /* NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE */
{ "nVdash", 0x22AE }, /* DOES NOT FORCE */
{ "nabla",  0x2207 }, /* NABLA */
{ "nacute", 0x0144 }, /* LATIN SMALL LETTER N ACUTE */
{ "nap",    0x2249 }, /* NOT ALMOST EQUAL TO */
{ "napos",  0x0149 }, /* LATIN SMALL LETTER APOSTROPHE N */
{ "natur",  0x266E }, /* NATURAL */
{ "nbsp",        160  },   /* non-breaking space */
{ "ncaron", 0x0148 }, /* LATIN SMALL LETTER N HACEK */
{ "ncedil", 0x0146 }, /* LATIN SMALL LETTER N CEDILLA */
{ "ncong",  0x2247 }, /* NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO */
{ "ncy",    0x043D }, /* CYRILLIC SMALL LETTER EN */
{ "ndash",  0x2013 }, /* EN DASH */
{ "ne",     0x2260 }, /* NOT EQUAL TO */
{ "nearr",  0x2197 }, /* UPPER RIGHT ARROW */
{ "nequiv", 0x2262 }, /* NOT IDENTICAL TO */
{ "nexist", 0x2204 }, /* THERE DOES NOT EXIST */
{ "nge",    0x2271 }, /* NEITHER GREATER THAN NOR EQUAL TO */
{ "nges",   0x2271 }, /* NEITHER GREATER THAN NOR EQUAL TO */
{ "ngr",    0x03BD }, /* GREEK SMALL LETTER NU */
{ "ngt",    0x226F }, /* NOT GREATER THAN */
{ "nhArr",  0x21CE }, /* LEFT RIGHT DOUBLE ARROW WITH STROKE */
{ "nharr",  0x21AE }, /* LEFT RIGHT ARROW WITH STROKE */
{ "ni",     0x220B }, /* CONTAINS AS MEMBER */
{ "njcy",   0x045A }, /* CYRILLIC SMALL LETTER NJE */
{ "nlArr",  0x21CD }, /* LEFT DOUBLE ARROW WITH STROKE */
{ "nlarr",  0x219A }, /* LEFT ARROW WITH STROKE */
{ "nldr",   0x2025 }, /* TWO DOT LEADER */
{ "nle",    0x2270 }, /* NEITHER LESS THAN NOR EQUAL TO */
{ "nles",   0x2270 }, /* NEITHER LESS THAN NOR EQUAL TO */
{ "nlt",    0x226E }, /* NOT LESS THAN */
{ "nltri",  0x22EA }, /* NOT NORMAL SUBGROUP OF */
{ "nltrie", 0x22EC }, /* NOT NORMAL SUBGROUP OF OR EQUAL TO */
{ "nmid",   0x2224 }, /* DOES NOT DIVIDE */
{ "not",         172  },   /* negation sign */
{ "notin",  0x2209 }, /* NOT AN ELEMENT OF */
{ "npar",   0x2226 }, /* NOT PARALLEL TO */
{ "npr",    0x2280 }, /* DOES NOT PRECEDE */
{ "npre",   0x22E0 }, /* DOES NOT PRECEDE OR EQUAL */
{ "nrArr",  0x21CF }, /* RIGHT DOUBLE ARROW WITH STROKE */
{ "nrarr",  0x219B }, /* RIGHT ARROW WITH STROKE */
{ "nrtri",  0x22EB }, /* DOES NOT CONTAIN AS NORMAL SUBGROUP */
{ "nrtrie", 0x22ED }, /* DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL */
{ "nsc",    0x2281 }, /* DOES NOT SUCCEED */
{ "nsce",   0x22E1 }, /* DOES NOT SUCCEED OR EQUAL */
{ "nsim",   0x2241 }, /* NOT TILDE */
{ "nsime",  0x2244 }, /* NOT ASYMPTOTICALLY EQUAL TO */
{ "nsub",   0x2284 }, /* NOT A SUBSET OF */
{ "nsube",  0x2288 }, /* NEITHER A SUBSET OF NOR EQUAL TO */
{ "nsup",   0x2285 }, /* NOT A SUPERSET OF */
{ "nsupe",  0x2289 }, /* NEITHER A SUPERSET OF NOR EQUAL TO */
{ "ntilde", 241  },   /* small n, tilde */ 
{ "nu",     0x03BD }, /* GREEK SMALL LETTER NU */
{ "num",    0x23 }, /* NUMBER SIGN */ /* FIX? */
{ "numero", 0x2116 }, /* NUMERO */
{ "numsp",  0x2007 }, /* FIGURE SPACE */
{ "nvDash", 0x22AD }, /* NOT TRUE */
{ "nvdash", 0x22AC }, /* DOES NOT PROVE */
{ "nwarr",  0x2196 }, /* UPPER LEFT ARROW */
{ "oS",     0x24C8 }, /* CIRCLED LATIN CAPITAL LETTER S */
{ "oacgr",  0x03CC }, /* GREEK SMALL LETTER OMICRON TONOS */
{ "oacute", 243  },   /* small o, acute accent */ 
{ "oast",   0x229B }, /* CIRCLED ASTERISK OPERATOR */
{ "ocir",   0x229A }, /* CIRCLED RING OPERATOR */
{ "ocirc",  244  },   /* small o, circumflex accent */ 
{ "ocy",    0x043E }, /* CYRILLIC SMALL LETTER O */
{ "odash",  0x229D }, /* CIRCLED DASH */
{ "odblac", 0x0151 }, /* LATIN SMALL LETTER O DOUBLE ACUTE */
{ "odot",   0x2299 }, /* CIRCLED DOT OPERATOR */
{ "oelig",  339  }, 
{ "ogon",   0x02DB }, /* SPACING OGONEK */
{ "ogr",    0x03BF }, /* GREEK SMALL LETTER OMICRON */
{ "ograve", 242  },   /* small o, grave accent */ 
{ "ohacgr", 0x03CE }, /* GREEK SMALL LETTER OMEGA TONOS */
{ "ohgr",   0x03C9 }, /* GREEK SMALL LETTER OMEGA */
{ "ohm",    0x2126 }, /* OHM */
{ "olarr",  0x21BA }, /* ANTICLOCKWISE OPEN CIRCLE ARROW */
{ "oline",  8254 }, 
{ "omacr",  0x014D }, /* LATIN SMALL LETTER O MACRON */
{ "omega",  0x03C9 }, /* GREEK SMALL LETTER OMEGA */
{ "omicron",     959  }, 
{ "ominus", 0x2296 }, /* CIRCLED MINUS */
{ "oplus",  0x2295 }, /* CIRCLED PLUS */
{ "or",          8744 }, 
{ "orarr",  0x21BB }, /* CLOCKWISE OPEN CIRCLE ARROW */
{ "order",  0x2134 }, /* SCRIPT SMALL O */
{ "ordf",        170  },   /* feminine ordinal indicator */
{ "ordm",        186  },   /* masculine ordinal indicator */
{ "oslash", 248  },   /* small o, slash */ 
{ "osol",   0x2298 }, /* CIRCLED DIVISION SLASH */
{ "otilde", 245  },   /* small o, tilde */ 
{ "otimes", 0x2297 }, /* CIRCLED TIMES */
{ "ouml",        246  },   /* small o, dieresis or umlaut mark */ 
{ "par",    0x2225 }, /* PARALLEL TO */
{ "para",        182  },   /* paragraph sign */
{ "part",   0x2202 }, /* PARTIAL DIFFERENTIAL */
{ "pcy",    0x043F }, /* CYRILLIC SMALL LETTER PE */
{ "percnt", 0x25 }, /* PERCENT SIGN */
{ "period", 0x2e }, /* PERIOD */
{ "permil", 0x2030 }, /* PER MILLE SIGN */
{ "perp",   0x22A5 }, /* UP TACK */
{ "pgr",    0x03C0 }, /* GREEK SMALL LETTER PI */
{ "phgr",   0x03C6 }, /* GREEK SMALL LETTER PHI */
{ "phi",         966  }, 
{ "phis",   0x03C6 }, /* GREEK SMALL LETTER PHI */
{ "phiv",   0x03D5 }, /* GREEK SMALL LETTER SCRIPT PHI */
{ "phmmat", 0x2133 }, /* SCRIPT M */
{ "phone",  0x260E }, /* BLACK TELEPHONE */
{ "pi",     0x03C0 }, /* GREEK SMALL LETTER PI */
{ "piv",    0x03D6 }, /* GREEK SMALL LETTER OMEGA PI */
{ "planck", 0x210F }, /* PLANCK CONSTANT OVER 2 PI */
{ "plus",   0x2b }, /* PLUS SIGN */
{ "plusb",  0x229E }, /* SQUARED PLUS */
{ "plusdo", 0x2214 }, /* DOT PLUS */
{ "plusmn", 177  },   /* plus-or-minus sign */
{ "pound",       163  },   /* pound sign */
{ "pr",     0x227A }, /* PRECEDES */
{ "prime",  0x2032 }, /* PRIME */
{ "prnsim", 0x22E8 }, /* PRECEDES BUT NOT EQUIVALENT TO */
{ "prod",   0x220F }, /* N-ARY PRODUCT */
{ "prop",   0x221D }, /* PROPORTIONAL TO */
{ "prsim",  0x227E }, /* PRECEDES OR EQUIVALENT TO */
{ "psgr",   0x03C8 }, /* GREEK SMALL LETTER PSI */
{ "psi",    0x03C8 }, /* GREEK SMALL LETTER PSI */
{ "puncsp", 0x2008 }, /* PUNCTUATION SPACE */
{ "quest",  0x3f }, /* QUESTION MARK */
{ "quot",        '"'  },
{ "rAarr",  0x21DB }, /* RIGHT TRIPLE ARROW */
{ "rArr",   0x21D2 }, /* RIGHT DOUBLE ARROW */
{ "racute", 0x0155 }, /* LATIN SMALL LETTER R ACUTE */
{ "radic",  0x221A }, /* SQUARE ROOT */
{ "rang",   0x232A }, /* KET */
{ "raquo",  187  },   /* angle quotation mark, right */
{ "rarr",   0x2192 }, /* RIGHT ARROW */
{ "rarr2",  0x21C9 }, /* RIGHT PAIRED ARROWS */
{ "rarrhk", 0x21AA }, /* RIGHT ARROW WITH HOOK */
{ "rarrlp", 0x21AC }, /* RIGHT ARROW WITH LOOP */
{ "rarrtl", 0x21A3 }, /* RIGHT ARROW WITH TAIL */
{ "rarrw",  0x219D }, /* RIGHT WAVE ARROW */
{ "rarrw",  0x21DD }, /* RIGHT SQUIGGLE ARROW */
{ "rcaron", 0x0159 }, /* LATIN SMALL LETTER R HACEK */
{ "rcedil", 0x0157 }, /* LATIN SMALL LETTER R CEDILLA */
{ "rceil",  0x2309 }, /* RIGHT CEILING */
{ "rcub",   0x7d }, /* CLOSING CURLY BRACKET */
{ "rcy",    0x0440 }, /* CYRILLIC SMALL LETTER ER */
{ "rdquo",  0x201D }, /* DOUBLE COMMA QUOTATION MARK */
{ "rdquor", 0x201C }, /* DOUBLE TURNED COMMA QUOTATION MARK */
{ "real",   0x211C }, /* BLACK-LETTER R */
{ "rect",   0x25AD }, /* WHITE RECTANGLE */
{ "reg",         174  },   /* circled R registered sign */
{ "rfloor", 0x230B }, /* RIGHT FLOOR */
{ "rgr",    0x03C1 }, /* GREEK SMALL LETTER RHO */
{ "rhard",  0x21C1 }, /* RIGHT HARPOON WITH BARB DOWN */
{ "rharu",  0x21C0 }, /* RIGHT HARPOON WITH BARB UP */
{ "rho",    0x03C1 }, /* GREEK SMALL LETTER RHO */
{ "rhov",   0x03F1 }, /* GREEK SMALL LETTER TAILED RHO */
{ "ring",   0x02DA }, /* SPACING RING ABOVE */
{ "rlarr2", 0x21C4 }, /* RIGHT ARROW OVER LEFT ARROW */
{ "rlhar2", 0x21CC }, /* RIGHT HARPOON OVER LEFT HARPOON */
{ "rlm",         8207 },   /* right-to-left mark */
{ "rpar",   0x29 }, /* CLOSING PARENTHESIS */
{ "rsaquo", 8250 }, 
{ "rsh",    0x21B1 }, /* UP ARROW WITH TIP RIGHT */
{ "rsqb",   0x5d }, /* CLOSING SQUARE BRACKET */
{ "rsquo",  0x2019 }, /* SINGLE COMMA QUOTATION MARK */
{ "rsquor", 0x2018 }, /* SINGLE TURNED COMMA QUOTATION MARK */
{ "rthree", 0x22CC }, /* RIGHT SEMIDIRECT PRODUCT */
{ "rtimes", 0x22CA }, /* RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT */
{ "rtri",   0x25B9 }, /* WHITE RIGHT POINTING SMALL TRIANGLE */
{ "rtrie",  0x22B5 }, /* CONTAINS AS NORMAL SUBGROUP OR EQUAL TO */
{ "rtrif",  0x25B8 }, /* BLACK RIGHT POINTING SMALL TRIANGLE */
{ "rx",     0x211E }, /* PRESCRIPTION TAKE */
{ "sacute", 0x015B }, /* LATIN SMALL LETTER S ACUTE */
{ "samalg", 0x2210 }, /* N-ARY COPRODUCT */
{ "sbquo",  8218 }, 
{ "sc",     0x227B }, /* SUCCEEDS */
{ "scaron", 353  }, 
{ "sccue",  0x227D }, /* SUCCEEDS OR EQUAL TO */
{ "scedil", 0x015F }, /* LATIN SMALL LETTER S CEDILLA */
{ "scirc",  0x015D }, /* LATIN SMALL LETTER S CIRCUMFLEX */
{ "scnsim", 0x22E9 }, /* SUCCEEDS BUT NOT EQUIVALENT TO */
{ "scsim",  0x227F }, /* SUCCEEDS OR EQUIVALENT TO */
{ "scy",    0x0441 }, /* CYRILLIC SMALL LETTER ES */
{ "sdot",   0x22C5 }, /* DOT OPERATOR */
{ "sdotb",  0x22A1 }, /* SQUARED DOT OPERATOR */
{ "sect",        167  },   /* section sign */
{ "semi",   0x3b }, /* SEMICOLON */
{ "setmn",  0x2216 }, /* SET MINUS */
{ "sextile", 0x2736 }, /* SIX POINTED BLACK STAR */
{ "sfgr",   0x03C2 }, /* GREEK SMALL LETTER FINAL SIGMA */
{ "sgr",    0x03C3 }, /* GREEK SMALL LETTER SIGMA */
{ "sharp",  0x266F }, /* SHARP */
{ "shchcy", 0x0449 }, /* CYRILLIC SMALL LETTER SHCHA */
{ "shcy",   0x0448 }, /* CYRILLIC SMALL LETTER SHA */
{ "shy",         173  },   /* soft hyphen */
{ "sigma",  0x03C3 }, /* GREEK SMALL LETTER SIGMA */
{ "sigmaf", 962  }, 
{ "sigmav", 0x03C2 }, /* GREEK SMALL LETTER FINAL SIGMA */
{ "sim",    0x223C }, /* TILDE OPERATOR */
{ "sime",   0x2243 }, /* ASYMPTOTICALLY EQUAL TO */
{ "smile",  0x2323 }, /* SMILE */
{ "softcy", 0x044C }, /* CYRILLIC SMALL LETTER SOFT SIGN */
{ "sol",    0x2f }, /* SLASH */
{ "spades", 0x2660 }, /* BLACK SPADE SUIT */
{ "sqcap",  0x2293 }, /* SQUARE CAP */
{ "sqcup",  0x2294 }, /* SQUARE CUP */
{ "sqsub",  0x228F }, /* SQUARE IMAGE OF */
{ "sqsube", 0x2291 }, /* SQUARE IMAGE OF OR EQUAL TO */
{ "sqsup",  0x2290 }, /* SQUARE ORIGINAL OF */
{ "sqsupe", 0x2292 }, /* SQUARE ORIGINAL OF OR EQUAL TO */
{ "squ",    0x25A1 }, /* WHITE SQUARE */
{ "square", 0x25A1 }, /* WHITE SQUARE */
{ "squf",   0x25AA }, /* BLACK SMALL SQUARE */
{ "sstarf", 0x22C6 }, /* STAR OPERATOR */
{ "star",   0x2606 }, /* WHITE STAR */
{ "starf",  0x2605 }, /* BLACK STAR */
{ "sub",    0x2282 }, /* SUBSET OF */
{ "sube",   0x2286 }, /* SUBSET OF OR EQUAL TO */
{ "subnE",  0x228A }, /* SUBSET OF OR NOT EQUAL TO */
{ "sum",    0x2211 }, /* N-ARY SUMMATION */
{ "sung",   0x266A }, /* EIGHTH NOTE */
{ "sup",    0x2283 }, /* SUPERSET OF */
{ "sup1",        185  },   /* superscript 1 */
{ "sup2",        178  },   /* superscript 2 */
{ "sup3",        179  },   /* superscript 3 */
{ "supe",   0x2287 }, /* SUPERSET OF OR EQUAL TO */
{ "supnE",  0x228B }, /* SUPERSET OF OR NOT EQUAL TO */
{ "szlig",  223  },   /* small sharp s, German (sz ligature) */ 
{ "target", 0x2316 }, /* POSITION INDICATOR */
{ "tau",    0x03C4 }, /* GREEK SMALL LETTER TAU */
{ "tcaron", 0x0165 }, /* LATIN SMALL LETTER T HACEK */
{ "tcedil", 0x0163 }, /* LATIN SMALL LETTER T CEDILLA */
{ "tcy",    0x0442 }, /* CYRILLIC SMALL LETTER TE */
{ "tdot",   0x20DB }, /* NON-SPACING THREE DOTS ABOVE */
{ "telrec", 0x2315 }, /* TELEPHONE RECORDER */
{ "tgr",    0x03C4 }, /* GREEK SMALL LETTER TAU */
{ "there4", 0x2234 }, /* THEREFORE */
{ "theta",  952  }, 
{ "thetas", 0x03B8 }, /* GREEK SMALL LETTER THETA */
{ "thetasym",    977  }, 
{ "thetav", 0x03D1 }, /* GREEK SMALL LETTER SCRIPT THETA */
{ "thgr",   0x03B8 }, /* GREEK SMALL LETTER THETA */
{ "thinsp", 0x2009 }, /* THIN SPACE */
{ "thkap",  0x2248 }, /* ALMOST EQUAL TO */
{ "thksim", 0x223C }, /* TILDE OPERATOR */
{ "thorn",  254  },   /* small thorn, Icelandic */ 
{ "tilde",  0x02DC }, /* SPACING TILDE */
{ "tilde",  0x7e /*732*/  }, /* TILDE */
{ "times",  215  },   /* multiplication sign */ 
{ "timesb", 0x22A0 }, /* SQUARED TIMES */
{ "top",    0x22A4 }, /* DOWN TACK */
{ "tprime", 0x2034 }, /* TRIPLE PRIME */
{ "trade",  0x2122 }, /* TRADEMARK */
{ "trie",   0x225C }, /* DELTA EQUAL TO */
{ "tscy",   0x0446 }, /* CYRILLIC SMALL LETTER TSE */
{ "tshcy",  0x045B }, /* CYRILLIC SMALL LETTER TSHE */
{ "tstrok", 0x0167 }, /* LATIN SMALL LETTER T BAR */
{ "twixt",  0x226C }, /* BETWEEN */
{ "uArr",   0x21D1 }, /* UP DOUBLE ARROW */
{ "uacgr",  0x03CD }, /* GREEK SMALL LETTER UPSILON TONOS */
{ "uacute", 250  },   /* small u, acute accent */ 
{ "uarr",   0x2191 }, /* UP ARROW */
{ "uarr2",  0x21C8 }, /* UP PAIRED ARROWS */
{ "ubrcy",  0x045E }, /* CYRILLIC SMALL LETTER SHORT U */
{ "ubreve", 0x016D }, /* LATIN SMALL LETTER U BREVE */
{ "ucirc",  251  },   /* small u, circumflex accent */ 
{ "ucy",    0x0443 }, /* CYRILLIC SMALL LETTER U */
{ "udblac", 0x0171 }, /* LATIN SMALL LETTER U DOUBLE ACUTE */
{ "udiagr", 0x03B0 }, /* GREEK SMALL LETTER UPSILON DIAERESIS TONOS */
{ "udigr",  0x03CB }, /* GREEK SMALL LETTER UPSILON DIAERESIS */
{ "ugr",    0x03C5 }, /* GREEK SMALL LETTER UPSILON */
{ "ugrave", 249  },   /* small u, grave accent */ 
{ "uharl",  0x21BF }, /* UP HARPOON WITH BARB LEFT */
{ "uharr",  0x21BE }, /* UP HARPOON WITH BARB RIGHT */
{ "uhblk",  0x2580 }, /* UPPER HALF BLOCK */
{ "ulcorn", 0x231C }, /* TOP LEFT CORNER */
{ "ulcrop", 0x230F }, /* TOP LEFT CROP */
{ "umacr",  0x016B }, /* LATIN SMALL LETTER U MACRON */
{ "uml",         168  },   /* spacing diaresis */
{ "uogon",  0x0173 }, /* LATIN SMALL LETTER U OGONEK */
{ "uplus",  0x228E }, /* MULTISET UNION */
{ "upsi",   0x03C5 }, /* GREEK SMALL LETTER UPSILON */
{ "upsih",  978  }, 
{ "upsilon",     965  }, 
{ "urcorn", 0x231D }, /* TOP RIGHT CORNER */
{ "urcrop", 0x230E }, /* TOP RIGHT CROP */
{ "uring",  0x016F }, /* LATIN SMALL LETTER U RING */
{ "utilde", 0x0169 }, /* LATIN SMALL LETTER U TILDE */
{ "utri",   0x25B5 }, /* WHITE UP POINTING SMALL TRIANGLE */
{ "utrif",  0x25B4 }, /* BLACK UP POINTING SMALL TRIANGLE */
{ "uuml",        252  },   /* small u, dieresis or umlaut mark */ 
{ "vArr",   0x21D5 }, /* UP DOWN DOUBLE ARROW */
{ "vDash",  0x22A8 }, /* TRUE */
{ "varr",   0x2195 }, /* UP DOWN ARROW */
{ "vcy",    0x0432 }, /* CYRILLIC SMALL LETTER VE */
{ "vdash",  0x22A2 }, /* RIGHT TACK */
{ "veebar", 0x22BB }, /* XOR */
{ "vellip", 0x22EE }, /* VERTICAL ELLIPSIS */
{ "verbar", 0x7c }, /* VERTICAL BAR */
{ "vltri",  0x22B2 }, /* NORMAL SUBGROUP OF */
{ "vprime", 0x2032 }, /* PRIME */
{ "vprop",  0x221D }, /* PROPORTIONAL TO */
{ "vrtri",  0x22B3 }, /* CONTAINS AS NORMAL SUBGROUP */
{ "wcirc",  0x0175 }, /* LATIN SMALL LETTER W CIRCUMFLEX */
{ "wedgeq", 0x2259 }, /* ESTIMATES */
{ "weierp", 0x2118 }, /* SCRIPT P */
{ "wreath", 0x2240 }, /* WREATH PRODUCT */
{ "xcirc",  0x25CB }, /* WHITE CIRCLE */
{ "xdtri",  0x25BD }, /* WHITE DOWN POINTING TRIANGLE */
{ "xgr",    0x03BE }, /* GREEK SMALL LETTER XI */
{ "xi",     0x03BE }, /* GREEK SMALL LETTER XI */
{ "xutri",  0x25B3 }, /* WHITE UP POINTING TRIANGLE */
{ "yacute", 253  },   /* small y, acute accent */ 
{ "yacy",   0x044F }, /* CYRILLIC SMALL LETTER IA */
{ "ycirc",  0x0177 }, /* LATIN SMALL LETTER Y CIRCUMFLEX */
{ "ycy",    0x044B }, /* CYRILLIC SMALL LETTER YERI */
{ "yen",         165  },   /* yen sign */
{ "yicy",   0x0457 }, /* CYRILLIC SMALL LETTER YI */
{ "yucy",   0x044E }, /* CYRILLIC SMALL LETTER IU */
{ "yuml",        255  },   /* small y, dieresis or umlaut mark */
{ "zacute", 0x017A }, /* LATIN SMALL LETTER Z ACUTE */
{ "zcaron", 0x017E }, /* LATIN SMALL LETTER Z HACEK */
{ "zcy",    0x0437 }, /* CYRILLIC SMALL LETTER ZE */
{ "zdot",   0x017C }, /* LATIN SMALL LETTER Z DOT */
{ "zeta",   0x03B6 }, /* GREEK SMALL LETTER ZETA */
{ "zgr",    0x03B6 }, /* GREEK SMALL LETTER ZETA */
{ "zhcy",   0x0436 }, /* CYRILLIC SMALL LETTER ZHE */
{ "zwj",         8205 },   /* zero width joiner */
{ "zwnj",        8204 },   /* zero width non-joiner */
/* Accents */
/* Added from Unicode obsolete UNI2SGML.TXT */
/* Arrows */
/* Greek */
/* ISO-8859-1 entities */
/* Latin Extended-A */ 
/* Letter type characters */ 
/* Math characters */
/* Misc tech characters */
/* Punctuation */
